{% set name = "atom-ml" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce53de39e5d21e80b707a9439751ee530b5207ac4b7a0759b7fe00309752bd44

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    # This section is required to correctly rerender skip statement
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip >=24.0
    - pdm >=2.12.4
    - pdm-pep517 >=1.1.4  # Use pdm-backend from next release
  run:
    - python
    - beartype >=0.16.4
    - category_encoders >=2.6.3
    - dill >=0.3.6
    - featuretools >=1.28.0
    - gplearn >=0.4.2
    - imbalanced-learn >=0.12.0
    - ipython >=8.11.0
    - ipywidgets >=8.1.1
    - joblib >=1.3.1
    - matplotlib-base >=3.7.2
    - mlflow >=2.10.2
    - nltk >=3.8.1
    - numpy >=1.23.0
    - optuna >=3.4.0
    - pandas >=2.1.2
    - plotly >=5.18.0
    - scikit-learn >=1.4.1.post1
    - scipy >=1.10.1
    - shap >=0.43.0
    - sktime-all-extras >=0.26.0
    - statsmodels >=0.14.1
    - zoofs >=0.1.25
  run_constrained:
    - botorch >= 0.8.5
    - catboost >=1.2
    - dask >=2024.2.0
    - explainerdashboard >=0.4.5
    - gradio >= 3.44.4
    - lightgbm >=4.1.0
    - modin-ray >=0.25.0
    - polars >=0.20.7
    - pyarrow >=15.0.0
    - pyspark >=3.5.0
    - ray-serve >=2.9.1
    - requests >=2.31.0
    - scikit-learn-intelex >=2023.2.1  # [x86]
    - schemdraw >=0.16
    - statsforecast >=1.6.0
    - sweetviz >=2.3.1
    - wordcloud >=1.9.2
    - py-xgboost >=2.0.0  # [not win]

test:
  requires:
    - pip >=24.0
    - pytest >= 7.2.1
  source_files:
    - tests
  commands:
    - pip install -U dagshub  # Not available in conda-forge
    - export GIT_PYTHON_REFRESH=quiet  # Required to make dagshub import work
    - pytest

about:
  home: http://github.com/tvdboom/ATOM
  license: MIT
  license_file: LICENSE
  summary: A Python package for fast exploration of machine learning pipelines
  description: |
    During the exploration phase of a machine learning project, a data
    scientist tries to find the optimal pipeline for his specific use case.
    This usually involves applying standard data cleaning steps, creating
    or selecting useful features, trying out different models, etc. Testing
    multiple pipelines requires many lines of code, and writing it all in
    the same notebook often makes it long and cluttered. On the other hand,
    using multiple notebooks makes it harder to compare the results and to
    keep an overview. On top of that, refactoring the code for every test
    can be time-consuming. How many times have you conducted the same action
    to pre-process a raw dataset? How many times have you copy-and-pasted
    code from an old repository to re-use it in a new use case?
    ATOM is here to help solve these common issues. The package acts as
    a wrapper of the whole machine learning pipeline, helping the data
    scientist to rapidly find a good model for his problem. Avoid
    endless imports and documentation lookups. Avoid rewriting the same
    code over and over again. With just a few lines of code, it's now
    possible to perform basic data cleaning steps, select relevant
    features and compare the performance of multiple models on a given
    dataset, providing quick insights on which pipeline performs best
    for the task at hand.
  doc_url: https://tvdboom.github.io/ATOM/
  dev_url: http://github.com/tvdboom/ATOM/tree/development

extra:
  recipe-maintainers:
    - tvdboom
